version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" 
    schedule:
      interval: "daily"
    assignees:
      - "Coho04"
    reviewers:
      - "Coho04"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
    - "Coho04"
    reviewers:
    - "Coho04"